[tox]
min_version = 4.0
envlist = 
    py314-django{60, 52}-wagtail{74, 70}
    py313-django{60, 52}-wagtail{74, 70}
    py312-django{60, 52}-wagtail{74, 70}
    py311-django52-wagtail{74, 70}
    py310-django52-wagtail{74, 70}
isolated_build = True

[testenv]
runner = uv-venv-lock-runner
commands = pytest
dependency_groups = 
    django52wagtail70: django52wagtail70
    django52wagtail74: django52wagtail74
    django60wagtail70: django60wagtail70
    django60wagtail74: django60wagtail74